name: Deploy to GCP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.svcaccount }}
          project_id: tensile-tenure-423308-e5

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=./tensile-tenure-423308-e5-0fa52aa16d6a.json


      - name: Deploy to Cloud Run
        run: |
          gcloud functions deploy testjestaxel\                       
          --gen2 \
          --runtime=nodejs20 \
          --region=us-east1 \
          --source=. \
          --entry-point=helloGET \
          --trigger-http
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.project_id }}
