name: Deploy to GCP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.svcaccount }}
          project_id: tensile-tenure-423308-e5

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=./tensile-tenure-423308-e5-0fa52aa16d6a.json

      - name: Run install
        run: npm i

      - name: Run unit tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: fc11a0ce-3fc8-4e47-861f-b38caef8e088
          slug: imxale/test-jest

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter tests
        run: |
          jmeter -n -t tests/stress/test_plan.jmx -l tests/stress/report/result.jtl -e -o tests/stress/report/ -Jjmeter.save.saveservice.output_format=csv -Jjmeter.save.saveservice.filename=tests/stress/report/result.csv

      - name: Install latency-lingo-cli
        run: |
          curl -L https://github.com/latency-lingo/cli/releases/latest/download/latency-lingo-cli_darwin_amd64.tar.gz \
           | tar -xz

      - name: Publish JMeter report to Lingo
        run: |
          ./latency-lingo-cli publish --file ./tests/stress/report/result.jtl --label "checkout flow" --api-key 814f97a2-f518-4384-94dc-dea39bc494fc