name: Deploy to GCP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.svcaccount }}
          project_id: tensile-tenure-423308-e5

      - name: Authenticate with gcloud
        run: |
          echo "$SVCACCOUNT" > /tmp/keyfile.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/keyfile.json"
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy test-jest-axel --image gcr.io/tensile-tenure-423308-e5/YOUR_IMAGE_NAME --platform managed --region us-east1
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.project_id }}
